[build]
# Custom install step so torch+cpu doesn’t timeout
builder = "NIXPACKS"
buildCommand = "pip install --only-binary=:all: -r requirements.txt -f https://download.pytorch.org/whl/cpu"

[deploy]
startCommand = "uvicorn backend:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
